### ISSUE TITLE
Crashes if language version is a string in the config.

### ISSUE THREAD

**Issue by vangorra** [jolicode/JoliCi#69]
``` yml
# The language specific base vm to use for this repository
language: node_js

# The node.js version to install
node_js: "0.12.7"
...
```

```
PHP Warning:  Invalid argument supplied for foreach() in phar:///home/robbiev/Documents/git/velocity-teamcity-reporter/jolici.phar/src/Joli/JoliCi/BuildStrategy/TravisCiBuildStrategy.php on line 281
PHP Catchable fatal error:  Argument 2 passed to Joli\JoliCi\Matrix::setDimension() must be of the type array, string given, called in phar:///home/robbiev/Documents/git/velocity-teamcity-reporter/jolici.phar/src/Joli/JoliCi/BuildStrategy/TravisCiBuildStrategy.php on line 311 and defined in phar:///home/robbiev/Documents/git/velocity-teamcity-reporter/jolici.phar/src/Joli/JoliCi/Matrix.php on line 26
```

If I change the config to the following, executing proceeds as expected.

``` yml
# The language specific base vm to use for this repository
language: node_js

# The node.js version to install
node_js: 
  - "0.12.7"
...
```

This use case should probably be handled considering the first config is valid and travis-ci will run it.
